### ISSUE TITLE
Expose `sources` directly instead of a `isEmpty` method?

### ISSUE THREAD

**Issue by stevemao** [grncdr/merge-stream#21]
This way you can actually get the list of `sources` and makes it more flexible.

**Comment by shinnn** [comment]
+1

I didn't realize that this module has the `isEmpty` method since it's not documented.

**Comment by stevemao** [comment]
It needs to be immutable though.

**Comment by grncdr** [comment]
> It needs to be immutable though.

:+1:

TBH though, "makes it more flexible" isn't a great reason for a feature IMO. Can we have some concrete use cases?

**Comment by stevemao** [comment]
similar reason why we need `isEmpty`. I just want to extend this so you can see "how many" and "what are they" but don't want them to be changed.

**Comment by grncdr** [comment]
Sure, but it's not a concrete use case. If you I'm looking for something more like: I have this problem to solve, and `merge-stream` almost works, but it would be very helpful if I could get a reference to all of the input streams.

Taking `isEmpty` as an example, the problem was that an empty merge stream would never emit `end`, and if you couldn't see that it a stream was empty before calling `pipe`, it was very difficult to understand why your program never finished. I'd expect we can find a similar motivating use case for exposing `sources`, but I don't know what it is yet.

**Comment by stevemao** [comment]
Thanks @grncdr , it makes sense. @shinnn maybe we should just add `isEmpty` to the doc and do 1.0.0 release?

**Comment by grncdr** [comment]
> Thanks @grncdr , it makes sense. @shinnn maybe we should just add isEmpty to the doc and do 1.0.0 release?

I like this idea. Releasing `1.0.0` now means consumers can add `^1.0.0` to their dependencies and get this enhancement in the future.

**Comment by grncdr** [comment]
:+1:

**Comment by stevemao** [comment]
Let's make a release if you guys are happy :)

**Comment by shinnn** [comment]
e973cf43ef0edda5d4e3b08b07040d4039822734
